# Generated by Django 2.2.1 on 2019-06-28 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190628_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 11, 46, 54, 589068, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
